### ISSUE TITLE
middleware per tessere sanitarie per raspberry pi

### ISSUE THREAD

**Issue by nestukh** [amusarra/raspberry-pi-access-via-ts-cns#1]
salve, il tuo è un bel progetto! Ho provato a replicarlo ma mi sono fermato, non riesco a trovare i driver middleware `libbit4*pki.so` per la mia tessera sanitaria che funzionino su raspberry pi (3b) con desktop.
Li ho trovati solo per linux i386 o x64, non per architettura arm:
https://sistemats1.sanita.finanze.it/portale/elenco-driver-cittadini-modalita-accesso
Riesco a farli funzionare a linea di comando emulando i386 via qemu e chroot (avendo un lettore smartcard compatibile con linux), usando
`pkcs11-tool --login --test --module /usr/lib/bit4id/libbit4xpki.so -t -l`
ma firefox diventa troooppo lento (emulando i386 firefox su un raspberry pi arm a 32 bit...), talvolta ritorna solo `bus error` (tipico di qemu). 
Tu dove li hai trovati?

**Comment by amusarra** [comment]
Ciao @nestukh grazie per il tuo feedback. In realtà non ti serve il driver specifico se il tuo lettore è CCID compliant. Per esempio io uso un lettore Bit4Id CCID compatibile che funziona con i driver standard di Linux Debian.

**Comment by nestukh** [comment]
no, non il driver per il lettore, ma per la tessera sanitaria come smartcard! Al link che ho postato ci sono i driver per le tessere in sé, che cambiano a seconda del carta non del lettore.
Edit: potrei confondermi: mi stai dicendo che i driver per la ts/cns proposti alla pagina (oltre ai driver per il lettore) sono tutti compresi nei repo linux e non serve scaricarli dai siti ministeriali?

**Comment by amusarra** [comment]
Faccio uso dell'implementazione standard PKCS#11 di OpenSC, come ho scritto sia sul README sia sull'articolo, e per la login con la mia CNS non trovato nessun problema. Tu hai quindi provato a fare la login utilizzando i moduli standard PKCS#11 e non ha funzionato?

<img width="1011" alt="Schermata 2021-10-19 alle 21 32 03" src="https://user-images.githubusercontent.com/708110/137978393-154460c2-cd1d-4722-bbb5-9270ff061d6a.png">

Dall'articolo https://www.dontesta.it/2020/07/17/raspberry-pi-esempio-applicazione-ts-cns-smartcard/
> PC/SC Middleware: Middleware per la gestione e comunicazione per le Smart Card e Smart Card Reader.
> OpenSC: OpenSC fornisce una serie di librerie e utilità per lavorare con le Smart Card. Il suo focus principale è sulle schede che supportano le operazioni crittografiche e ne facilitano l’uso in applicazioni di sicurezza come l’autenticazione, la crittografia della posta e le firme digitali. OpenSC implementa le API standard su Smart Card, ad es. API PKCS#11, Minidriver per Smart Card di Windows e macOS CryptoTokenKit.

**Comment by amusarra** [comment]
Per ulteriore informazione, la mia TS-CNS usa il chip ST-MICROELECTRONIS

**Comment by nestukh** [comment]
Penso di essermi confuso perché il mio lettore richiede driver particolari (non è il massimo). Prenderò quello che hai detto, credo che su raspberry pi funzionerà meglio.

Quindi:
- il pacchetto [`libccid`](https://packages.debian.org/stable/libccid)  copre i driver per i lettori smartcard _CCID compliant_
- il pacchetto [`opensc-pkcs11`](https://packages.debian.org/stable/opensc-pkcs11)  copre i middleware per le smartcard _PKCS#11 compliant_

Come poi ho letto [qui](https://github.com/OpenSC/OpenSC/wiki/Italian-CNS-and-CIE), i middleware per le tessere forniti dalle regioni servono solo per gli eventuali servizi sanitari accessori implementati, _oltre_ alla semplice autenticazione via pin, sempre coperta dal driver generico PKCS#11. 
Non è esattamente chiaro per un noefita.
Chiudo il thread come risolto. Grazie per il supporto!
